### ISSUE TITLE
Crash when server is installing

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [LOENS2/pterodactyl_exporter#21]
**Describe the bug**
If a server is installing and Pterodactyl Exporter attempts to get metrics for it, the program will crash.

**To Reproduce**
1. Have a server on installing mode
2. Run Pterodactyl Exporter
3. Wait for it to fetch metrics and then it will crash

**Expected behavior**
It not to crash and ignore the server.

**Screenshots**

**Desktop (please complete the following information):**
 - Distribution: Ubuntu
 - Browser Chrome
 - Version 120.0.6099.71
 - Python version 3.11
 - Prometheus version latest
 - Pterodactyl Panel version latest

**Additional context**
Error:
```
{'errors': [{'code': 'ServerStateConflictException', 'status': '409', 'detail': 'This server has not yet completed its installation process, please try again later.'}]}
{'errors': [{'code': 'ServerStateConflictException', 'status': '409', 'detail': 'This server has not yet completed its installation process, please try again later.'}]}
{'errors': [{'code': 'ServerStateConflictException', 'status': '409', 'detail': 'This server has not yet completed its installation process, please try again later.'}]}
{'errors': [{'code': 'ServerStateConflictException', 'status': '409', 'detail': 'This server has not yet completed its installation process, please try again later.'}]}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/container/.python/pterodactyl_exporter/pterodactyl_exporter.py", line 42, in <module>
    main()
  File "/home/container/.python/pterodactyl_exporter/pterodactyl_exporter.py", line 32, in main
    metrics = http_client.get_metrics()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.python/pterodactyl_exporter/http_client.py", line 63, in get_metrics
    get_metrics()
  File "/home/container/.python/pterodactyl_exporter/http_client.py", line 63, in get_metrics
    get_metrics()
  File "/home/container/.python/pterodactyl_exporter/http_client.py", line 63, in get_metrics
    get_metrics()
  File "/home/container/.python/pterodactyl_exporter/http_client.py", line 64, in get_metrics
    metrics = response["attributes"]['resources']
              ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'
```

**Comment by LOENS2** [comment]
That's very interesting.
I tried switching some of my servers to install mode in Pterodactly and it has the expected behaviour.

![image](https://github.com/LOENS2/pterodactyl_exporter/assets/72134951/b2b9f865-9d95-45cf-957e-12f2134aac7a)

All of the performance metrics should be 0 as the panel return a null value for the server.

Because I (of course) couldn't reproduce it on my side so far I have to ask you some further questions.

1. What is your installation type (Pip, Git, Docker, Pterodactyl Egg)?
2. Do you use the latest version of pterodactyl_exporter?
3. What is your config? Which type of `server_list_type:` do you use. 
4. Is your panel version 1.11.5? (Just to rule out any differences of the setup)

Thank you very much for your issue report and for using the correct template :D

**Comment by WilliamDavidHarrison** [comment]
1. I was using an partially modified version of the Pterodactyl egg, however the only changes were the variable descriptions (not names). Nothing else in the egg was modified.
2. I was using the latest version.
3. I was using a client Pterodactyl API key on an account with administrator permissions with `admin-all` set in the config.
4. Yep, both my panel and wings are up to date.

Also, I just wanted to note, I have 2 panels both running the exact same configuration of Pterodactyl exporter and the error occurs on both.

**Comment by LOENS2** [comment]
Good News! I managed to replicate the error in my testing setup:

![Bildschirmfoto vom 2023-12-14 11-27-22](https://github.com/LOENS2/pterodactyl_exporter/assets/72134951/cfa75b90-fb4e-4508-92a7-2b5b112caeab)

The odd thing is, that i couldn't replicate it on my production system, so I have to further investigate the error. But that should be quite easy now. I'm very busy right now so that has to wait until the coming weekend.

**Comment by WilliamDavidHarrison** [comment]
@LOENS2 Thank you for the response. For some reason now, it just randomly crashes even when all servers are online. I don't have the crash logs for it as of now however. Do you think it would be possible to add a error handler so it won't crash but just log the error to console?

**Comment by LOENS2** [comment]
Interesting... The errors while requesting the data from the API should already be shown in the logs. The easiest way to build an error handler would be to enclose the get methods in a try catch. And you could try to delete the `.python` folder and reinstall the server.
I'll do that in my troubleshooting anyway, but I still don't understand, why this error exists in the first place. It seems like after the installation process is finished the API doesn't respond for a few seconds, but that case should already be covered by my testing code, however the exporter still crashes. I'll keep you updated on my progress.

**Comment by WilliamDavidHarrison** [comment]
I'll keep you updated as well, I have deleted the `.python` folder and reinstalled the server. I appreciate your quick responses and for actually looking into the matter.

**Comment by LOENS2** [comment]
I found the problem! As I correctly suspected, the API responds with an empty string, which is exactly what crashes the exporter. This should be quite an easy fix.

**Comment by LOENS2** [comment]
Well, the problem seems to be more complicated, than I initially thought. I basically have to rewrite the request functions to avoid this error and this will take some time.

**Comment by LOENS2** [comment]
Good News! I solved the problem. The error merely existed due to my bad code. Instead of raising an exception and handling it I tried to solve the problem with some stupid workaround. I've now implemented the exceptions properly, which adds extended debugging as well. 

In order to use the new release, just use the "reinstall server" for the exporter in Pterodactyl Panel. Please tell me whether it works now or not.

This was solved in 3fd3632

**Comment by WilliamDavidHarrison** [comment]
The server does come online, and I'll monitor the server for around 24 hours to see if there are any errors that occur. Thanks for looking into this!

**Comment by WilliamDavidHarrison** [comment]
@LOENS2 This error has popped up in my console quite a bit:
```
An error occured:
Expecting value: line 1 column 1 (char 0)
```

**Comment by WilliamDavidHarrison** [comment]
@LOENS2 These errors also are occurring:
```
An error occured:
Metrics: 
{
    "errors": [
        {
            "code": "NotFoundHttpException",
            "status": "404",
            "detail": "The requested resource could not be found on the server."
        }
    ]
}
An error occured:
Metrics: 
{
    "errors": [
        {
            "code": "ServerStateConflictException",
            "status": "409",
            "detail": "This server has not yet completed its installation process, please try again later."
        }
    ]
}
```

**Comment by LOENS2** [comment]
@wdhdev Those error messages look fine to me. As long as the exporter keeps running, they're nothing to be concerned about.  I assume that those errors occurred before as well, but I just didn't show them. Now they are shown due to the extended debugging I added.

**Comment by wdhdev** [comment]
@LOENS2 Thank you for the confirmation. Thank you for your support with this issue :)
